%YAML:1.0
# Default params
# camera_calibration_file: "kinect_default.yaml"
# rgb_topic: "camera/rgb/image_raw"
# depth_topic: "camera/depth/image_raw"
# aruco_dic: "ARUCO"
# aruco_poses_file: "aruco_poses"
# marker_size: 0.1778
# aruco_distance: 4
camera_calibration_file: "../../../src/ros_autonomous_robot/kinect_default.yaml"
rgb_topic: "camera/rgb/image_raw"
depth_topic: "camera/depth/image_raw"
aruco_dic: "ARUCO"
aruco_poses_file: "aruco_poses"
aruco_distance: 4
aruco_marker_size: 0.1778








