%YAML:1.0
# Default params
# camera_calibration_file: "kinect_default.yaml"
# rgb_topic: "camera/rgb/image_raw"
# depth_topic: "camera/depth/image_raw"
# aruco_dic: "ARUCO"
# aruco_poses_file: "aruco_poses"
# marker_size: 0.1778
# aruco_max_distance: 4(-1 means infinite )
# aruco_offset_distance: 0.4(meters) distance offset of real position and where aruco will be saved
camera_calibration_file: "../../../src/ros_autonomous_robot/kinect_default.yaml"
rgb_topic: "camera/rgb/image_raw"
depth_topic: "camera/depth/image_raw"
aruco_dic: "ARUCO"
aruco_poses_file: "aruco_poses"
aruco_max_distance: -1
aruco_marker_size: 0.1778
aruco_offset_distance: 0.4



